name: Deploy

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  check:
    uses: ./.github/workflows/check.yml

  deploy:
    needs: [check]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - run: cd example && nix run .#deploy -- -n
